services:
  db:
    env_file:
      - ".env"
    image: postgres
    restart: always
    networks:
      - prisma-network
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 60s

  server:
    build: 
      context: .  
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true  # Keeps the container running for debugging
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ".env"
    networks:
      - prisma-network

networks:
  prisma-network:
    name: prisma-network